[workspace]
members = [
    "halo2",
    "halo2_proofs",
    "arithmetic/ff",
    "arithmetic/group",
    "arithmetic/pairing",
    "arithmetic/curves",
    "arithmetic/pasta_curves",
    "primitives/poseidon"
]
